### ISSUE TITLE
pf Bug 

### ISSUE THREAD

**Issue by Cyber-Raptor** [dsiekiera/foe-helfer-extension#1101] opened 2020-05-27 15:26 UTC
in my bar i have 0 pfs , but in i have 3800 
i tested in flash , do not appear right ?
but in htlm5 and i guess its foe helper info ..
 i reload foe ( with htlm5 and appers all my pfs,but if i open a ge all pfs goes to 0 , but in ge info i had all pfs .. looks this print : https://prnt.sc/soui3p

**Comment by scibuff** [comment] 2020-05-27 15:31
Duplicate of #1025, #1044, #1059 and #1089. Fixed in the next release

**Closed** 2020-05-29 08:20 UTC
Labels: Dublette / Duplicate, Extension - Bug, Nächstes Update - Next update
