### ISSUE TITLE
AF 200 FP quest not showing up

### ISSUE THREAD

**Issue by NickRing** [dsiekiera/foe-helfer-extension#1793] opened 2021-01-25 01:37 UTC
I have noticed that in my SAM world, I can have two FP quests, and both are shown in the "GB Cost Calculator" and "GB Calculator". In another world, I am in AF and it only shows the 99 FPs quest (while I have 99 FP and 200 FP quests).

Having a quick search, it seems the issue is here : https://github.com/dsiekiera/foe-helfer-extension/blob/master/js/web/calculator/js/calculator.js#L234

> if (Quest.questGiver.id === 'scientist' && Quest.type === 'generic' && Quest.abortable === true) {

The questGiver.id is "trader" (see JSON below):

      {
        "id": 933010,
        "windowTitle": "Recurring Quest - Greva Darn",
        "title": "A Long Nap",
        "type": "generic",
        "questGiver": {
          "id": "trader",
          "name": "Greva Darn",
          "__class__": "QuestGiver"
        },
        "priority": 933010,
        "state": "accepted",
        "autoCompleted": false,
        "successConditions": [
          {
            "id": 1,
            "iconType": "icon_quest_alchemie",
            "description": "Spend 200 Forge Points",
            "hint": "",
            "hintIcon": "",
            "maxProgress": 200,
            "payload": [],
            "flags": [],
            "guidanceActions": [],
            "__class__": "QuestSuccessCondition"
          }
        ],
        "successConditionGroups": [
          {
            "conditionIds": [
              1
            ],
            "type": "none",
            "__class__": "SuccessConditionGroup"
          }
        ],
        "rewards": [
          {
            "hidden": true,
            "quest_id": 933010,
            "random": true,
            "isBoosted": false,
            "__class__": "QuestReward"
          }
        ],
        "genericRewards": [],
        "headline": "Noble Ruler!",
        "description": "After so long without sleeping, I'm getting really, really tired. If I go to sleep now, I bet I could hibernate.",
        "accomplishedHeadline": "Your Grace!",
        "accomplishedDescription": "Good morning! I feel like I slept for ages. What day is it?",
        "abortable": true,
        "category": "story",
        "context": "",
        "flags": [],
        "__class__": "Quest"
      },

**Comment by outoftheline** [comment] 2021-01-25 07:25
Thank you for reporting this issue

**Comment by Th3C0D3R** [comment] 2021-01-25 15:31
This is the only one which make problem because we cant safely detect this quest as a FP Requrring Quest because of its different questqiver type.
We maybe do a hardcoding decision there if its the only quest missing.
We maybe just do an ID compare because this is the same every time.

**Comment by Th3C0D3R** [comment] 2021-01-25 15:40
Fixed in beta branch for next update

**Comment by Th3C0D3R** [comment] 2021-01-26 04:08
The issue is open as long as the update is not released ;)

**Closed** 2021-02-13 13:48 UTC
Labels: Extension - Bug, Nächstes Update / Next Update
