### ISSUE TITLE
Scouting Time Issue: Cannot open campaign map

### ISSUE THREAD

**Issue by franzalex** [dsiekiera/foe-helfer-extension#2327] opened 2022-02-22 16:29 UTC
I am now in Space Age Mars and collecting Mars Ore while scouting provinces on the SAM map.
After the update to version 2.6.0.0, I am unable to open the campaign map.

When I click on the continent map icon, the browser stops responding and I have to close and reload the tab.

I did a bit of debugging and found that the part that causes the extension to stop working is [scoutingtimes.js#L247](../blob/2e0a52a456ba99e6a843c6170f67d3891895bb10/js/web/scoutingtimes/js/scoutingtimes.js#L247). When I have DevTools open, the debugger pauses at L247 with the message _paused before potential out-of-memory crash_.

My browser is Microsoft Edge Version 98.0.1108.56 (Official build) (64-bit).

**Comment by mainIine** [comment] 2022-02-22 16:33
Duplicate of #2326

**Closed as completed** 2022-02-22 19:00 UTC
Labels: Next Version
