### ISSUE TITLE
Statistics: Remove empty/null values

### ISSUE THREAD

**Issue by fbakkes** [dsiekiera/foe-helfer-extension#1568] opened 2020-08-19 11:20 UTC
I think this happens when stats are updated for settlement units and the main city units are not updated.
![image](https://user-images.githubusercontent.com/8653771/90628561-1e17e480-e21e-11ea-91c6-27be3787db76.png)

**Comment by GeniusTimo** [comment] 2020-08-19 11:39
Duplicate of #1522

**Closed** 2020-09-04 17:22 UTC
Labels: Dublette / Duplicate, Nächstes Update / Next Update
