### ISSUE TITLE
zz - Gildengefechte - Keine Anzahl der Kämpf mehr

### ISSUE THREAD

**Issue by DaEgo** [dsiekiera/foe-helfer-extension#1768] opened 2021-01-19 11:08 UTC
Es wird in den Gildengefechten auf dem Beta keine absolvierten Kämpfe mehr gezählt,
die Seite ist einfach leer.

In the guild battles on the beta, completed battles are no longer counted,
the page is just blank.

![2021-01-19 12_07_35-BETA CF14](https://user-images.githubusercontent.com/1351055/105026589-fc31c080-5a4e-11eb-9b2f-fb3618f467f1.png)

**Comment by outoftheline** [comment] 2021-01-20 08:13
Kannst du ein paar weiterführende Infos geben? Welchen Browser nutzt du, gibt es in der Entwicklerkonsole (F12) einen Fehler?

Leider spielt keiner von uns Devs die GG in der Beta, weshalb wir den Fehler gerade nicht selbst untersuchen können und die nächste GG auf Beta startet erst in einer Woche.

**Comment by DaEgo** [comment] 2021-01-20 11:00
Gerne
Chrome Version 87.0.4280.141 (Offizieller Build) (64-Bit)
muss gleich mal updaten...

Beim ersten öffnen kommt das (also einmalig)

_main.js?v=2.5.4.4:434 TypeError: Cannot read property 'addon_portrait_id_pirate_chef' of null
    at Object.BuildPlayerContent (guildfights.js?v=2.5.4.4:223)
    at Object.ShowPlayerBox (guildfights.js?v=2.5.4.4:171)
    at Object.HandlePlayerLeaderboard (guildfights.js?v=2.5.4.4:121)
    at guildfights.js?v=2.5.4.4:29
    at _proxyAction (_main.js?v=2.5.4.4:432)
    at proxyAction (_main.js?v=2.5.4.4:443)
    at XMLHttpRequest.xhrOnLoadHandler (_main.js?v=2.5.4.4:532)

Wenn das Addon Fenster offen ist und bleibt , wiederholt er sich so:

TypeError: Cannot read property 'addon_portrait_id_pirate_chef' of null
    at Object.BuildPlayerContent (guildfights.js?v=2.5.4.4:223)
    at Object.HandlePlayerLeaderboard (guildfights.js?v=2.5.4.4:119)
    at guildfights.js?v=2.5.4.4:29
    at _proxyAction (_main.js?v=2.5.4.4:432)
    at proxyAction (_main.js?v=2.5.4.4:443)
    at XMLHttpRequest.xhrOnLoadHandler (_main.js?v=2.5.4.4:532)

ausgeklappte Info


_proxyAction | @ | _main.js?v=2.5.4.4:434
-- | -- | --
  | proxyAction | @ | _main.js?v=2.5.4.4:443
  | xhrOnLoadHandler | @ | _main.js?v=2.5.4.4:532
  | load (async) |   |  
  | XHR.send | @ | _main.js?v=2.5.4.4:546
  | load | @ | ForgeHX-a5e221c3.js:27918
  | __loadText | @ | ForgeHX-a5e221c3.js:27920
  | loadText | @ | ForgeHX-a5e221c3.js:27918
  | loadString | @ | ForgeHX-a5e221c3.js:28075
  | load | @ | ForgeHX-a5e221c3.js:28861
  | _loadRequest | @ | ForgeHX-a5e221c3.js:581
  | _send | @ | ForgeHX-a5e221c3.js:579
  | _doRequest | @ | ForgeHX-a5e221c3.js:577
  | _processNextRequest | @ | ForgeHX-a5e221c3.js:574
  | _pushRequest | @ | ForgeHX-a5e221c3.js:577
  | _sendAllBufferedRequests | @ | ForgeHX-a5e221c3.js:576
  | send | @ | ForgeHX-a5e221c3.js:572
  | call | @ | ForgeHX-a5e221c3.js:544
  | _callWithFuture | @ | ForgeHX-a5e221c3.js:556
  | getPlayerLeaderboard | @ | ForgeHX-a5e221c3.js:3916
  | execute | @ | ForgeHX-a5e221c3.js:3834
  | execute | @ | ForgeHX-a5e221c3.js:28943
  | routeEventToCommand | @ | ForgeHX-a5e221c3.js:28943
  | h | @ | ForgeHX-a5e221c3.js:28941
  | __dispatchEvent | @ | ForgeHX-a5e221c3.js:20
  | dispatchEvent | @ | ForgeHX-a5e221c3.js:17
  | dispatch | @ | ForgeHX-a5e221c3.js:530
  | _onComponentClick | @ | ForgeHX-a5e221c3.js:4002
  | routeEventToListener | @ | ForgeHX-a5e221c3.js:28948
  | k | @ | ForgeHX-a5e221c3.js:28947
  | __dispatchEvent | @ | ForgeHX-a5e221c3.js:20
  | __dispatch | @ | ForgeHX-a5e221c3.js:51
  | __dispatchStack | @ | ForgeHX-a5e221c3.js:28636
  | __onMouse | @ | ForgeHX-a5e221c3.js:28650
  | onMouseUp | @ | ForgeHX-a5e221c3.js:28629
  | dispatch | @ | ForgeHX-a5e221c3.js:27963
  | handleMouseEvent | @ | ForgeHX-a5e221c3.js:27933

**Comment by outoftheline** [comment] 2021-01-20 11:17
Danke, dann ist das vmtl der gleiche Fehler wie beim Moppelassistenten.

**Comment by dsiekiera** [comment] 2021-01-22 17:42
Duplicate of #1770

**Closed by dsiekiera** 2021-01-22 17:42 UTC
Labels: Extension - Bug, Nächstes Update / Next Update
