### ISSUE TITLE
Fall event helper

### ISSUE THREAD

**Issue by Dlonrab** [dsiekiera/foe-helfer-extension#1593] opened 2020-09-10 12:38 UTC
The last column of the vent helper screen ( Daily price chance per ingredient) is incorrect/not understandable?
In this specific example it should (?) read : 
.. Stars.........stars/ingredient.....daily price chance..........  chance/ingredient
.....1.......................1 ........................................ 6 % ................................... 6%
.....3 ......................1........................................14% ......................................4,7%   
.....2 ......................1........................................13%.......................................**_6.5 %_**                   

![afbeelding](https://user-images.githubusercontent.com/64436664/92729162-34731500-f372-11ea-8d87-9b12e8fcb95f.png)

**Comment by andrgin** [comment] 2020-09-10 12:40
Which version do you have installed?

**Comment by Dlonrab** [comment] 2020-09-10 12:45
Versie
2.5.0.0

**Comment by Dlonrab** [comment] 2020-09-10 12:50
Firefox: Version
    2.5.0.0
Player-ID:
    1908138
Guild-ID:
    6522
World:
    nl3

For Chrome
2.5.2.1
Player-ID:
1913246
Guild-ID:
6522
Wereld:
nl3

**Comment by andrgin** [comment] 2020-09-10 15:35
Do you have this problem with Chrome as well? This bug should be fixed with 2.5.2.1

**Comment by Dlonrab** [comment] 2020-09-10 17:35
This "bug" shows up as well in Firefox as Chrome as Opera as Vivaldi. Updated Firefox extension (automatic update were accidentally switched off)

In the old version 2.5.0.0 also the second column (stars (or steps) per ingredient) was producing confusing/weird numbers. This was corrected after updating to version 2.5.2.1.

Although the presentation now is a bit weird (is does not show the chances for winning the daily update per choice but the total number of selections you have to make to have an average chance of 1 to win the daily price.

This seems a bit contra intuitive, but I could live with that. Depends of clarity of the text above that column.

**Comment by andrgin** [comment] 2020-09-10 18:02
Sorry I did not look at the screenshot carefully enough on my phone. In version 2.5.0 costs have been wrong. The current 2.5.2.1 is working as intended:

The event helper is not done just for the fall event, but for all events that follow the the same "pick one of X chests" system. This is for example the football/soccer event or the sprint event (the one with the frog and the lake), so the general names are used.

Costs: Tell you how much event currency (in this case ingredeants) are used
Steps: Shows the progress towards the main prize (in this case stars) you get
Daily special chance: This is the chance for the daily prize

Costs/step: Shows how many ingredeants you need per star. For this event it is always 1, but for other events it can be different.

Cost/prize: Shows how many ingredeants you need per daily prize. The reason why we use cost/prize is because for other events numbers would get really low (imagine a 0.094% chance per energy drink). Also if you know the costs/daily prize you can calculate how many daily prizes you will get on average for the event currency you have. Lets say cost/daily prize is 1000 and you have 7000 energy drinks, you will get 7 daily prizes, so if you are going for an event building that needs 10 upgrade kits it might not be a smart idea.

In case of the current fall event you should not always pick the cheapest daily price, because you have to consider different ingredeants as well. If you are low on ingredeants it might be better to pick the ingredeants you have the most. If you have 30 each it might be better to go for daily prize chance.

**Comment by Dlonrab** [comment] 2020-09-10 20:00
Thanks for your explanation. I agree with you regarding the made 
considerations.

Tony

Op 10-9-2020 om 20:03 schreef Gindi4711:

**Closed** 2021-01-23 09:51 UTC
Labels: Wont-Fix
