### ISSUE TITLE
Uncorrect calculation FP

### ISSUE THREAD

**Issue by MakcuMuM** [dsiekiera/foe-helfer-extension#1097] opened 2020-05-27 10:14 UTC
![download](https://user-images.githubusercontent.com/834814/83007329-cfd6b900-a013-11ea-8e52-871a1e1b7cf5.png)

**Comment by dsiekiera** [comment] 2020-05-27 10:17
Duplicate of #1089

**Closed** 2020-05-29 08:19 UTC
Labels: Dublette / Duplicate, Extension - Bug, Nächstes Update - Next update
