### ISSUE TITLE
Motivation activity on SE2 gives error

### ISSUE THREAD

**Issue by chve14** [dsiekiera/foe-helfer-extension#791] opened 2020-04-12 11:44 UTC
POST:
https://api.foe-rechner.de/OtherPlayersMotivation/?player_id=94805&guild_id=3408&world=se2

Response:
Fatal error: Uncaught ADODB_Exception: mysqli error: [1146: Table 'foecre_site3.other_players_service_se2' doesn't exist] in EXECUTE("SELECT ops_id FROM other_players_service_se2 WHERE player_id = 94805 AND other_id = 653523 ") in /usr/www/users/foecre/api.foe-rechner.de/_inc/vendor/adodb/adodb-exceptions.inc.php:86 Stack trace: #0 /usr/www/users/foecre/api.foe-rechner.de/_inc/vendor/adodb/adodb.inc.php(897): adodb_throw('mysqli', 'EXECUTE', 1146, 'Table 'foecre_s...', 'SELECT \n\t\t\tops_...', false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/api.foe-rechner.de/_inc/vendor/adodb/adodb.inc.php(861): ADOConnection->_Execute('SELECT \n\t\t\tops_...') #2 /usr/www/users/foecre/api.foe-rechner.de/_inc/classes/db.php(118): ADOConnection->Execute('SELECT \n\t\t\tops_...', Array) #3 /usr/www/users/foecre/api.foe-rechner.de/OtherPlayersMotivation/index.php(94): db->db_execute('SELECT \n\t\t\tops_...', Array) #4 {main} thrown in /usr/www/users/foecre/api.foe-rechner.de/_inc/vendor/adodb/adodb-exceptions.inc.php on line 86

**Comment by dsiekiera** [comment] 2020-05-27 16:34
Duplicate of #529

**Closed** 2021-01-04 18:30 UTC
Labels: HP - Bug
