### ISSUE TITLE
Infobox - double messages (GBG)

### ISSUE THREAD

**Issue by Arklur** [dsiekiera/foe-helfer-extension#1496] opened 2020-07-13 06:43 UTC
There are 2 entries for each GBG action.

![](https://i.imgur.com/3cmbQ35.png)

Battles/negotiations generate 1 empty and 1 correct message, taking sectors seems like showing the same message twice.

**Comment by SillyDevil** [comment] 2020-07-13 13:47
and I get 4 messages, sometimes blank messages too
![Screenshot_3](https://user-images.githubusercontent.com/65982368/87311856-19c22280-c520-11ea-9aac-04f4e175d55c.png)

![Screenshot_3](https://user-images.githubusercontent.com/65982368/87311813-0911ac80-c520-11ea-8c12-4b5ccb682c18.png)

**Comment by GeniusTimo** [comment] 2020-07-13 15:05
Duplicate of #1439

**Comment by anthill1953** [comment] 2020-07-14 16:00
Same problem

**Comment by Th3C0D3R** [comment] 2020-07-14 17:55
Fixed in next version

**Comment by Th3C0D3R** [comment] 2020-07-14 17:59
Or maybe not. We habe to look into it

**Closed** 2020-07-14 18:04 UTC
Labels: Dublette / Duplicate, Extension - Bug, Nächstes Update - Next update

**Comment by Arklur** [comment] 2020-07-15 14:30
If it matters, I can confirm this seems to be fixed. The box is open quite for some time, and I haven't seen any empty messages.

**Comment by anthill1953** [comment] 2020-07-15 16:15
it's good on my end, much less confusing now. thanks
