### ISSUE TITLE
FOE Helper -incidents counter not correct

### ISSUE THREAD

**Issue by ScriptAdel** [dsiekiera/foe-helfer-extension#1494] opened 2020-07-12 18:48 UTC
**Incidents counter not showing correct number** of incidents until you collect
this is screenshot before Iopen Tab
![image](https://user-images.githubusercontent.com/65903928/87254153-29daf300-c489-11ea-8bf8-d8455d139860.png)

And this picture after i open Tab
![image](https://user-images.githubusercontent.com/65903928/87254186-5f7fdc00-c489-11ea-8647-b056954af03a.png)

**Comment by GeniusTimo** [comment] 2020-07-12 18:58
Duplicate of #1321

**Closed** 2020-07-14 18:20 UTC
Labels: Dublette / Duplicate, Extension - Bug, Nächstes Update - Next update
