### ISSUE TITLE
Wish last inlog friends to see stil active.

### ISSUE THREAD

**Issue by fransrd** [dsiekiera/foe-helfer-extension#832] opened 2020-04-19 20:13 UTC
wish.

Is it possible to show which friend has been active (friends tavern)? Last week, 14 days or month?

**Comment by andrgin** [comment] 2020-04-19 21:01
If you have an account on foe-rechner.de Statistics -> Motivieren/Polieren -> Motivation report

**Comment by dsiekiera** [comment] 2020-05-27 16:34
Duplicate of #529

**Closed** 2020-07-20 19:37 UTC
Labels: Frage / Ask
