### ISSUE TITLE
Ancient Egypt Settlement not calculating loot correctly

### ISSUE THREAD

**Issue by PeacefulWrestler** [dsiekiera/foe-helfer-extension#1019] opened 2020-05-12 14:45 UTC
![image](https://user-images.githubusercontent.com/65238623/81705564-77c68100-946f-11ea-8189-58e52d7be734.png)

I currently have 764 Loot in the settlement. The tool seems to calculate each building independently to see if I have enough Loot for that building. 

Clearly the calculation for total Loot required is also visibly wrong.

Version 2.4.5

**Comment by andrgin** [comment] 2020-05-12 21:31
tldr: The 450 for the pyramid is not correct. This should be 800. I guess this is caused by sacrificial offerings required is 0.

Explanation:
Procession: 29 sacrificial offerings are missing so you need 300 loot to produce 30 (because you can only produce in batches of 5)
Luxury estate: 34 pottery are required (350 loot) plus 35 (29+6) sacrificial offerings (350 loot) means total 700
Pyramid: 42 pottery (34+8) require 450 loot, 35 (29+6) require 350 loot so total 800.
If you have 764 loot you are missing 36)

**Comment by PeacefulWrestler** [comment] 2020-05-12 21:39
I don't know what is happening under the hood, so to speak. All I know is that when I unlocked the Place of Prayer the tool showed that I had an excess of loot, and this caused me to delete my armies to make room for goods building. Then suddenly it showed me missing loot again.

Now I know to be extra careful if one or more of the unlocks require 0 goods of one or more type.

**Comment by andrgin** [comment] 2020-05-13 22:45
The display bug 450 instead of 800 will be fixed in the next update.

For the wrong sum: I cant reproduce that.

**Closed** 2020-05-24 17:06 UTC
Labels: Extension - Bug, Nächstes Update - Next update
