### ISSUE TITLE
Tech Tree Research Costs are wrong

### ISSUE THREAD

**Issue by MarcAroma** [dsiekiera/foe-helfer-extension#1862] opened 2021-02-16 15:26 UTC
I was in the Iron Age. According to your Tech Tree Research Costs Tool I had more then enough resources (goods & forge points) to complete the Colonial Age - including optional technologies. 

But once I reached the end of the Late Middle Ages, I had only 6 FP left, and suddenly also missing also some goods. :( 

Luckily I did not start the Colonial Age. 

But there is definitely something wrong with your calculations there, especially when moving up more then 1 age...

**Comment by outoftheline** [comment] 2021-02-16 16:59
Did you research everything or leave out the dead ends? If you researched the dead ends, did you click on the options to include them?

**Comment by MarcAroma** [comment] 2021-02-16 17:21
Yes I clicked on the boxes to include them, but left 2 out because I don't need them. However, I should have had some forge points (and goods) left over after completing the Colonial Age - I had only 6 FP left before starting (I did not do that) the Colonial Age, and I am also missing goods. That has definitely nothing to do with the dead ends...

**Comment by andrgin** [comment] 2021-02-20 12:19
Are you sure that you used the Foe helper tool and not the ingame tool because the ingame tool has the exact same bug that you describe?

**Comment by MarcAroma** [comment] 2021-02-20 13:03
Well, at the top bar is says "Tech Tree Research Cost - FOE Helper", and it is a tool...

<img width="590" alt="Screen Shot 2021-02-20 at 13 57 47" src="https://user-images.githubusercontent.com/3120697/108596253-14656a00-7384-11eb-86a5-f1a00ee7f98b.png">

**Comment by MarcAroma** [comment] 2021-02-20 13:57
I use the AddOn FOE-Helper in my browser on my laptop, what else is there?

**Comment by andrgin** [comment] 2021-02-22 22:07
I tried reproducing this with my iron age world including the optional technologies and my FP cost exactly matched the values from the fandom wiki.

Can you remember what you did before opening the tool the first time. Did you already research some technologies before? Did you receive or spend FP before opening the tool?

How much was the FP difference and which goods were missing?

**Comment by MarcAroma** [comment] 2021-02-22 23:30
Well, as I said, I had only 6 FP left before starting the Colonial Age, and I think I should have had a couple of hundreds left after completing the Colonial Age... And what exact goods were missing, I am not sure, not many, I think 3 or 4 different ones.

After completing Early Middle Ages all seemed fine as far as I could see, but after completing the High Middle Ages I though something went wrong, as in how the hell should I be able to complete the Colonial Age with these resources left...

I am playing in 5 Worlds, so I guess I know my way a little around...

So what 2 different tools are you talking about, I am using your AddOn, what other FOE-Helper Tools are there?

**Comment by andrgin** [comment] 2021-02-23 22:26
There are 2 tools:
.) The Foe helper tool like shown in your screenshot
.) The ingame tool that Inno tried to copy from us, but this tool has exactly the bug you are talking about as it only shows cost of colonial age and not the sum of all the ages

![Screen](https://user-images.githubusercontent.com/55417498/108916327-60d3d280-762e-11eb-991b-3d41e13c4fea.png)

Are you really sure you did not accidently use the ingame tool as I cant think of any situation where the Foe helper tool could be off by a whole age.

Btw. the account shown in the screenshot only has a few technologies resarched from EMA.

**Comment by MarcAroma** [comment] 2021-02-24 10:33
OK, just to make sure I understand you correctly:

- In you screenshot are two tools, left the FOE-Helper Tool.
- And right the Research Costs by InnoGames, I guess what you called the ingame tool...?

Again yes, I am sure I used your FOE-Helper Tool (I was not even aware of the Research Tool until now...)

I am sorry that I did not take screenshots before and after the time-move. Howevernly because you can not replicate that error, does not mean that it doesn't exist. So please stop questioning me. 
I know what your tool showed me, otherwise I would have waited and gathered those missing FP and goods and attempted the time move later once I had those all complete plus reserves...

**Comment by andrgin** [comment] 2021-02-24 12:30
No matter if it there is actually a bug or not: If I cant reproduce I cant fix it.

So far nobody else has reported wrong values except for the definition which technologies should be counted as optional and which not. As long as we can not gather additional information to help identifying the possible reason I am closing this issue.

**Closed by andrgin** 2021-02-24 12:30 UTC
Labels: Nicht reproduzierbar / Not reproducible, Untersuche - Investigating
