### ISSUE TITLE
Unnecessary warning when donating to GBs - FP packs in stock

### ISSUE THREAD

**Issue by Arklur** [dsiekiera/foe-helfer-extension#1114] opened 2020-05-28 11:38 UTC
Probably this came in the last update, but I don't feel the need of it / would like to turn this off.
![](https://i.imgur.com/JUzPQIW.png)

Since 99,9999% of the time obviously I won't have enough FPs to "snipe", the numbers being in red are misleading to me, and as I see, there is no option to disable it. In my opinion the previous version was much better, could you revert this change or add an option to disable this "conditional formatting"?

**Comment by Maurosen** [comment] 2020-05-28 13:05
I have the same Problem on Firefox. When i start the Game my Storage is ok. But when i open a Lg my Storage go to 0

**Comment by dsiekiera** [comment] 2020-05-28 13:54
Duplicate of #1089

**Comment by andrgin** [comment] 2020-05-28 13:55
This is caused by a change on Inno side how to handle  FP storage, so there is no way to revert back.
We will have a fix for the new logic in the next update.

**Comment by Arklur** [comment] 2020-05-28 14:54
Yeah, I've realized I totally misunderstood what's the warning about, or well, didn't notice the "FP stock" dropped to 0, then I noticed the issue is already reported and pinned, that's why I closed this one.

+1: seems like it was always worked like that (_no change on your side and no need to revert anything_), I just haven't seen this since I always had enough FPs...sorry for the misleading report, next time I'll try to be more cautious.

**Comment by dsiekiera** [comment] 2020-05-28 14:55
Its ok ;-)

**Closed** 2020-05-29 08:21 UTC
Labels: Dublette / Duplicate, Extension - Bug, Nächstes Update - Next update
