### ISSUE TITLE
Error with pomo statistics

### ISSUE THREAD

**Issue by Pantea729** [dsiekiera/foe-helfer-extension#1102] opened 2020-05-27 15:31 UTC
Hi,

I saw that similar defects have already been fixed but all PO/MO statistics don't work in my case.
Below you can find the stacktrace for social interactions.

Thanks by advance for your help and congrats for your great job

Fatal error: Uncaught ADODB_Exception: mysqli error: [1146: Table 'foecre_site3.other_players_service_entries_fr18' doesn't exist] in EXECUTE("SELECT ops.ops_id, ops.other_id, ops.other_name, ops.is_neighbor, ops.is_friend, ops.is_guild_member, (SELECT UNIX_TIMESTAMP(opse.date_visit) FROM other_players_service_entries_fr18 opse WHERE opse.ops_id = ops.ops_id ORDER BY opse.date_visit DESC LIMIT 1) AS last_visit FROM other_players_service_fr18 ops WHERE ops.player_id = 8923934 AND ops.other_id = '679586' AND ops.world = 'fr18' ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1146, 'Table 'foecre_s...', 'SELECT \n\t\t\t\tops...', false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1216): ADOConnec in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79

**Comment by dsiekiera** [comment] 2020-05-27 16:30
Duplicate of #529 #745 #791 #832 #903 #1073

**Closed** 2021-01-04 18:03 UTC
