### ISSUE TITLE
Infobox Displaying 4 copies of Messages

### ISSUE THREAD

**Issue by Blue-w** [dsiekiera/foe-helfer-extension#1439] opened 2020-07-07 13:46 UTC
THe Infobox is displaying 4 copies of Messages

![infobox](https://user-images.githubusercontent.com/28864486/86790496-1a2f6900-c09b-11ea-912e-1d8d4e75496e.PNG)

**Comment by GeniusTimo** [comment] 2020-07-07 13:53
Duplicate of #1375 and fixed in the next update 😉

**Comment by andrgin** [comment] 2020-07-07 16:05
The bug in #1375 explains double messages, but if they appear 4 times there still seems something else going wrong.

**Comment by SillyDevil** [comment] 2020-07-07 23:29
I had raised #1375 yes now its 4 sometimes 3, at times there are blank messages giving only the timer (gbg time counter)

**Comment by SillyDevil** [comment] 2020-07-13 13:42
![Screenshot_2](https://user-images.githubusercontent.com/65982368/87311309-5fcab680-c51f-11ea-8d75-f1a085dbad7b.png)

Blank messages with gbg time

**Comment by dsiekiera** [comment] 2020-07-14 18:58
Duplicate of #1375

**Comment by SillyDevil** [comment] 2020-07-15 11:08
Problem still exist, but now there are two copies 
![Screenshot_2](https://user-images.githubusercontent.com/65982368/87538267-3c794600-c69c-11ea-9ed4-9320c84d4759.png)

**Comment by GeniusTimo** [comment] 2020-07-15 11:09
And you use the version 2.5.1.0?

**Comment by SillyDevil** [comment] 2020-07-15 11:15
yes I am using the version that is updated today
Regards
Vinayak Deshmukh

**Comment by GeniusTimo** [comment] 2020-07-15 11:20
Could you give more information about about your setup? For me this issue isn't reporducable
ℹ️ I deleted your comment to protect your real name

**Comment by SillyDevil** [comment] 2020-07-15 11:25
What information do you need, I will be glad to provide
Regards
Vinayak Deshmukh

**Comment by SillyDevil** [comment] 2020-07-15 11:26
what information do you need, I will be glad to share

**Comment by GeniusTimo** [comment] 2020-07-15 11:27
Have a look at [this pinned issue](https://github.com/dsiekiera/foe-helfer-extension/issues/620)
You may be able to configure your mail program so that your name is not inserted at the end (or simply reply here on GitHub)

**Comment by SillyDevil** [comment] 2020-07-15 11:27
yes I will reply here :) thank you

**Comment by SillyDevil** [comment] 2020-07-15 11:31
Windows 7 64 Bit
Chrome Version 83.0.4103.116 (Official Build) (64-bit

how do i check foe helper version?

**Comment by SillyDevil** [comment] 2020-07-15 11:32
foe version 2.5.1.0

**Comment by SillyDevil** [comment] 2020-07-15 11:32
foe version 2.5.1.0

**Comment by GeniusTimo** [comment] 2020-07-15 11:33
I really can't tell you, where this empty message is coming from - is this issue only in GBG or also other events?

**Comment by SillyDevil** [comment] 2020-07-15 11:35
Not sure if this is right, I tried F12
DevTools failed to load SourceMap: Could not load content for chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/vendor/dexie/dexie.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by SillyDevil** [comment] 2020-07-15 11:36
chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/js/web/_main/js/_main.js?v=2.5.1.0:515 Can't parse postData:  [{"__class__":"ServerRequest","requestData":[],"requestClass":"GuildBattlegroundService","requestMethod":"getPlayerLeaderboard","requestId":328}]

**Comment by GeniusTimo** [comment] 2020-07-15 11:38
> chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/js/web/_main/js/_main.js?v=2.5.1.0:515 Can't parse postData: [{"**class**":"ServerRequest","requestData":[],"requestClass":"GuildBattlegroundService","requestMethod":"getPlayerLeaderboard","requestId":328}]

That looks very interesting, thank you.

**Comment by SillyDevil** [comment] 2020-07-15 11:45
this message error is for everything, any message that comes, is duplicate in infobox

**Comment by SillyDevil** [comment] 2020-07-15 11:45
you are welcome :))

**Comment by GeniusTimo** [comment] 2020-07-15 12:03
I have changed a bit in the code, can you download this development version?
- Download [this archive](https://download.geniustimo.de/foe-helfer-extension.zip) and unzip it
- Go to `chrome://extensions`, enable the development mode and move the `.crx`-file from the extracted ZIP to the extension (drag and drop)
- now disbale the normale version of the helper
![grafik](https://user-images.githubusercontent.com/47282153/87542799-da244380-c6a3-11ea-9826-b244ec2dead4.png)
- you should now have this version installed, now reload the game and check, if this has solved the issue
![grafik](https://user-images.githubusercontent.com/47282153/87542858-ef996d80-c6a3-11ea-97d1-ba2d20c74091.png)
If you encounter any problems, let me know.

**Comment by SillyDevil** [comment] 2020-07-15 12:15
Thank you, I will try and let you know :)

**Comment by SillyDevil** [comment] 2020-07-15 12:19
I installed as you said, but this the error I got :  This extension is not listed in the Chrome Web Store and may have been added without your knowledge. Learn more

**Comment by SillyDevil** [comment] 2020-07-15 12:21
the extension is in disabled mode, cant enable it

**Comment by GeniusTimo** [comment] 2020-07-15 12:25
Interesting, I now uploaded the extracted extension as ZIP over [here](https://download.geniustimo.de/foe-helfer-extension.zip), unzip it to an new/empty folder and import it with "Load unpacked extension" in Chrome

**Comment by SillyDevil** [comment] 2020-07-15 12:38
okay

**Comment by SillyDevil** [comment] 2020-07-15 12:45
I tried again its same, plus now I cant even download again, it gives 404 error

**Comment by GeniusTimo** [comment] 2020-07-15 12:46
Sorry, my mistake - this link https://download.geniustimo.de/foe-helfer.zip

**Comment by SillyDevil** [comment] 2020-07-15 12:50
still same, its in disabled mode

**Comment by GeniusTimo** [comment] 2020-07-15 12:52
Have you removed the file from before? I can't figure out why it works for me otherwise.

**Comment by SillyDevil** [comment] 2020-07-15 12:57
yes i removed the file before, let me try refresh and do it again

**Comment by SillyDevil** [comment] 2020-07-15 12:58
![Screenshot_4](https://user-images.githubusercontent.com/65982368/87547577-9a615a00-c6ab-11ea-8eb6-532e1a42ecd2.png)

this is what i get

**Comment by SillyDevil** [comment] 2020-07-15 12:59
shall i try removing foe helper, instead of disable?

**Comment by GeniusTimo** [comment] 2020-07-15 13:00
Do you have Discord? There I may be able to help more directly 😅

**Comment by SillyDevil** [comment] 2020-07-15 13:04
yes I have discord

**Comment by SillyDevil** [comment] 2020-07-15 13:05
Vini#9663

**Closed** 2020-07-24 15:33 UTC
Labels: Extension - Bug, Nächstes Update / Next Update
