### ISSUE TITLE
Side bar overlap

### ISSUE THREAD

**Issue by SureshotQXC** [dsiekiera/foe-helfer-extension#1661] opened 2020-12-08 02:46 UTC
As of today, the FOE helper menu bar on the right of the page is overlapping the game menu bar above.  It is blocking the down arrow of the game sidebar.  This is happening on both chrome and firefox and observed on 4 different PCs as well as a laptop.

Additionally
![Foe sidebar](https://user-images.githubusercontent.com/75652931/101431814-30f41900-38e2-11eb-9435-05c0b1332e6c.jpg)

**Comment by Th3C0D3R** [comment] 2020-12-08 03:30
This is known and will be fixed in the next release. Our menu will get a new location

**Comment by coderwolf2015** [comment] 2020-12-08 05:55
In the mean time you can use browser zoom features to potentially bypass the problem.  I am using 67% zoom in chrome.
![2020-12-08 00_53_20-Window](https://user-images.githubusercontent.com/13156002/101445734-08731b80-38f0-11eb-8db7-98cb35708776.png)

**Comment by dsiekiera** [comment] 2020-12-08 21:02
Duplicate of #1657

**Closed** 2020-12-08 21:16 UTC
