### ISSUE TITLE
Suggesting FOE Helper Show Which Player Attacking What Sector in Guild Battlegrounds

### ISSUE THREAD

**Issue by AlephTangent** [dsiekiera/foe-helfer-extension#674] opened 2020-03-23 17:09 UTC
I do not know if this is possible.

In our Guild we have had issues with GuildMembers attacking sectors in Guild Battlegrounds we don't want them to attack.  We have no way of determining who is failing to honour our treaties with other Guilds.  If possible, this would be a valuable tool for us.  

I've been using FOE helper for a few weeks, and it has been generally helpful.

**Comment by andrgin** [comment] 2020-03-23 17:35
Would be nice, but unfortunately this is not possible, because we do not get this information.

**Comment by scibuff** [comment] 2020-03-23 20:03
It is possible to see who's doing what in battleground (you can see the number of negotiations and/or fights increasing for guild members) but you cannot see in which sector they are doing it.

I've written a devtools plugin to do just that. @andrgin would you guys be interested in help/colab to add such functionality (you can see it under foe-gbg in my github)

**Comment by andrgin** [comment] 2020-03-23 20:20
We already have a feature to check how many negotiations/fights since the last time you opened it the list.
The problem is that you dont know where the players attacked.

**Comment by scibuff** [comment] 2020-03-23 20:48
Really? Under which section? (I know foe doesn't provide the data for which sector(s) were affected)

**Comment by capshort** [comment] 2020-03-28 09:12
I understand that it cannot always be determined who did what but it would already be helpful if you know _some_ of the culprits so that you can write them a pm to respect the treaty. At the moment I regularly open the battlegrounds map and look out for changes in points in the critical sectors. Afterwards I have a look at who did anything since my last visit. Oftentimes it is unmistakable who failed to respect the treaty and in the cases that it is not you at least know a pool of suspects.
There should be a way to have this evaluated automatically by the extension, correct?

**Comment by scibuff** [comment] 2020-03-28 12:55
Looking at the data, it is possible to gather progress on each sector (every time you open the gbg screen), that means it is possible to do a difference between now and the last time you opened it. But, it wouldn't be possible, for example, to know if the sector changed the owner several times during that period. Let's say guild A owns the sector A1 now. You leave FOE and while you're away, your guild conquers A1 and guild B then conquers A1 from your guild. You return to gbg and there's no data that your guild ever had A1 --- we'd see only that the last time you were in gbg A1 was owned by guild A and now it is owned by guild B.

**Comment by capshort** [comment] 2020-03-28 13:23
So being offline for too long a period leaves room for a corner case, I see. Fortunately a freshly conquered sector cannot change owners too fast but after 4 hours the earliest. I can live with not being able to draw conclusions for a part of the day, as long as I know that the information I _do_ get is correct. Correct me if I'm wrong but the information should be correct if my last snapshot was less than 4 hours ago.

**Comment by outoftheline** [comment] 2020-07-20 14:52
> Correct me if I'm wrong but the information should be correct if my last snapshot was less than 4 hours ago.

You're not wrong :)

Closing this issue.

**Closed by outoftheline** 2020-07-20 14:52 UTC
Labels: Wird nicht umgesetzt / Will not be implemented
