### ISSUE TITLE
Negotiation didn't pop-up

### ISSUE THREAD

**Issue by ffblackice** [dsiekiera/foe-helfer-extension#1342] opened 2020-06-28 11:45 UTC
See screen capture. It didn't pop up on the US9 server.
![Helper did not pop up for negotiation](https://user-images.githubusercontent.com/67544241/85946564-29801b00-b913-11ea-917c-2d0b8a2ef44a.jpg)

It does pop-up on the beta server.

**Comment by scibuff** [comment] 2020-06-28 11:51
As per Inno requirements the negotiation helper has been removed from the Guild Battlegrounds. It should still function as before in other parts of the game (e.g. Guild Expedition)

Please see: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper

**Comment by ffblackice** [comment] 2020-06-28 12:07
It is still function on beta server?
![Helper negotiation still function on beta server](https://user-images.githubusercontent.com/67544241/85947041-64d01900-b916-11ea-8707-43eb4c068003.jpg)

**Comment by andrgin** [comment] 2020-06-28 12:17
Do you have version 2.5.0 installed?
If yes then Inno must have changed something when transmitting data.
I cant test it atm because my beta account ist not in GBG

**Comment by GeniusTimo** [comment] 2020-06-28 12:33
If you open the window manually, you will see the data of the last negotiation (which is not very helpful)

![grafik](https://user-images.githubusercontent.com/47282153/85947613-1fc6d980-b94c-11ea-99a6-00c66a048f63.png)
![grafik](https://user-images.githubusercontent.com/47282153/85947624-281f1480-b94c-11ea-8330-06df7a12618c.png)

**Comment by ffblackice** [comment] 2020-06-28 13:55
Yes, I have upgraded to latest version. In the beta server it won't pop-up by itself, but can be opened manually, and it is the current negotiation, tried already.

**Comment by GeniusTimo** [comment] 2020-06-28 14:07
I still can't reproduce this issue 🤔

**Comment by andrgin** [comment] 2020-06-28 16:49
With the next update the negotiation helper button will switch to red again if you start a GBG negotiation to avoid further confusion.

**Comment by andrgin** [comment] 2020-06-29 20:04
Released with 2.5.0.1

**Closed by andrgin** 2020-06-29 20:04 UTC
Labels: Extension - Bug, Nächstes Update - Next update
