### ISSUE TITLE
Disapearing FPs

### ISSUE THREAD

**Issue by TBSailor** [dsiekiera/foe-helfer-extension#1100] opened 2020-05-27 14:35 UTC
Open other player GB to add FPs in a 190% thread, my stored FPs go to zero.
Does not happen in Ice Dragon, without FOE-Helper
Cleared cache and reset in Chrome

1.179.ba1aa26c3b4 (27.05.2020 10:29),
 TBSailor (8716032), 
us6, en_US, 
WEB 7,1,1,0, 
Windows 10, 
Chrome/81.0.4044.138, 
1920x990, 
OpenGL Vendor=WebKit Version=WebGL 2.0 (OpenGL ES 3.0 Chromium) Renderer=WebKit WebGL GLSL=WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium) (512 MB VRAM)

**Comment by dsiekiera** [comment] 2020-05-27 14:36
Duplicate of #1089

**Comment by TBSailor** [comment] 2020-05-27 14:37
FPs show properly until GB window is opened

**Comment by dsiekiera** [comment] 2020-05-27 14:38
Thanks anyway for reporting. The next bug report is yours 😄

**Comment by TBSailor** [comment] 2020-05-27 14:39
Thank you for a great product



Best regards



Peter Albright

126 Buena Vista Drive

Daphne, AL 36526

251-776-3300


------ Original Message ------

**Closed** 2020-05-29 08:20 UTC
Labels: Dublette / Duplicate, Extension - Bug, Nächstes Update - Next update
